# Generated by Django 6.0 on 2026-02-15 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Teknik Informatika', max_length=100)),
                ('jenjang', models.CharField(choices=[('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='S1', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Jurusan',
            },
        ),
        migrations.CreateModel(
            name='KategoriVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('konten', models.TextField()),
                ('tanggal', models.DateField()),
                ('gambar', models.ImageField(blank=True, upload_to='kegiatan/')),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=20)),
                ('sks', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='PerguruanTinggi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Universitas Indonesia', max_length=200)),
                ('kode_pt', models.CharField(blank=True, help_text='Kode PT Dikti (Opsional)', max_length=20, null=True)),
                ('alamat', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Perguruan Tinggi',
            },
        ),
        migrations.CreateModel(
            name='TriDharma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('PENELITIAN', 'Penelitian'), ('PKM', 'Pengabdian Masyarakat'), ('PUBLIKASI', 'Publikasi Jurnal/Buku')], max_length=20)),
                ('judul', models.CharField(max_length=200)),
                ('tahun', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True)),
                ('link_eksternal', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-tahun'],
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mahasiswa/')),
                ('jurusan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa', to='main.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(help_text='Contoh: Kelas A, TI-2B, Pagi', max_length=50)),
                ('semester', models.CharField(help_text='Contoh: Ganjil 2023/2024', max_length=20)),
                ('tahun_ajaran', models.CharField(blank=True, max_length=20, null=True)),
                ('mahasiswa', models.ManyToManyField(blank=True, related_name='kelas_diambil', to='main.mahasiswa')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_set', to='main.matakuliah')),
            ],
            options={
                'verbose_name_plural': 'Kelas Perkuliahan',
            },
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_materi', models.CharField(max_length=100)),
                ('file_materi', models.FileField(upload_to='materi/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi', to='main.matakuliah')),
            ],
        ),
        migrations.AddField(
            model_name='jurusan',
            name='perguruan_tinggi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurusan', to='main.perguruantinggi'),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nidn', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profil/')),
                ('email', models.EmailField(max_length=254)),
                ('scholar_link', models.URLField(blank=True, verbose_name='Google Scholar URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SesiKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topik', models.CharField(max_length=200)),
                ('tanggal', models.DateField()),
                ('pertemuan_ke', models.PositiveIntegerField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_set', to='main.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='VideoYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('youtube_id', models.CharField(help_text='Contoh: dQw4w9WgXcQ', max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kategorivideo')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('H', 'Hadir'), ('S', 'Sakit'), ('I', 'Izin'), ('A', 'Alpha')], default='A', max_length=1)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mahasiswa')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sesikuliah')),
            ],
            options={
                'unique_together': {('sesi', 'mahasiswa')},
            },
        ),
    ]
